#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

. "${ROOT}/inc-sh/commit-automator.inc.sh"

usage() {
	USAGE="Usage: commit-automator install|prepare|register"
	echo "${USAGE}"
	exit 22
}

install() {
	if [ "$#" -lt 1 ]; then
		usage
	fi

	DIR=${1}
	shift
	HOOKS="${DIR}/.git/hooks"
	mkdir -p "${HOOKS}"
	cp "${ROOT}/hooks/prepare-commit-msg" "${HOOKS}/."
	echo -n "$(realpath $0) prepare " >>"${HOOKS}/prepare-commit-msg"
	echo '${COMMIT_MSG_FILE} ${BRANCH}' >>"${HOOKS}/prepare-commit-msg"
}

prepare() {
	local commit_file="${1}"
	shift

	local branch="${1}"
	shift

	local branch_file="${CONFIG_BRANCHES}/${branch}"

	if [ -f "${branch_file}" ]; then
		local issue=$(cat "${branch_file}")
		echo "" > "${commit_file}"
		git interpret-trailers --in-place --trailer "Issue: ${issue}" "${commit_file}"
	fi
}

register() {
	if [ "$#" -lt 2 ]; then
		usage
	fi

	BRANCH=${1}
	shift

	ISSUE=${1}
	shift

	mkdir -p "${CONFIG_BRANCHES}"
	BRANCH_FILE="${CONFIG_BRANCHES}/${BRANCH}"
	echo "${ISSUE}" >${BRANCH_FILE}
}

if [ "$#" -lt 1 ]; then
	usage
fi

ACTION=${1}
shift

case $ACTION in
install)
	install "$@"
	;;
prepare)
	prepare "$@"
	;;
register)
	register "$@"
	;;
*)
	usage
	;;
esac
