#!/usr/bin/env bash
set -euo pipefail
ROOT="$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"

ACTION=${1}
shift

case $ACTION in
     install)
        DIR=${1}
        shift
        HOOKS="${DIR}/.git/hooks"
        mkdir -p "${HOOKS}"
        cp "${ROOT}/hooks/prepare-commit-msg" "${HOOKS}/."
        ;;
esac
