name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]

    steps:
      - uses: actions/checkout@v2

      - name: Install Bats
        run: |
             wget -O bats.zip "https://github.com/sstephenson/bats/archive/master.zip"
             unzip bats.zip

      - name: Test
        run: |
          bats-master/bin/bats commit-automator.bats
