name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - uses: actions/checkout@v2

      - name: Run
        run: DIR="a" && mkdir -p "${DIR}" && HOOK=".git/hooks/prepare-commit-msg" && commit-automator install "${DIR}"

      - name: Test
        run: bats -r .
