name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11.0, windows-2019]

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - uses: actions/checkout@v2

      - name: Configure Comitter
        run: git config --global user.name "Test"; git config --global user.email "test@test.com"

      - name: Test
        run: bats -r .
